spring:
  datasource:
    password: q1w2e3r4
    url: jdbc:mysql://localhost:3306/teste?useSSL=false&useTimezone=true&serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: 398844415401-g0jtbv8rarp00dbf06etp19u5756hf8t.apps.googleusercontent.com
          clientSecret: 8N7Uasq1FkvTecl89uDneFDh
          scope:
           - email
           - profile